twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    globals:
        app_name: '%env(APP_NAME)%'
        app_version: '%env(APP_VERSION)%'
        app_domain: '%env(APP_DOMAIN)%'
        app_theme: '%env(APP_THEME)%'
        #app_default_module: '%env(DEFAULT_MODULE)%'
        form_service: '@App\Service\OrderFormView'
when@test:
    twig:
        strict_variables: true
