app_home:
  path: /
  controller: App\Controller\DefaultController::default

app_index:
  path: /index
  controller: App\Controller\DefaultController::index

app_inbox:
  path: /inbox
  controller: App\Controller\InboxController::inbox
