#deprecated
app_default:
  path: /
  controller: App\Controller\DefaultController::default

app_home:
  path: /
  controller: App\Controller\DefaultController::default

app_home_default:
  path: /home
  controller: App\Controller\DefaultController::home

#deprecated
app_index:
  path: /index
  controller: App\Controller\DefaultController::index

default:
  path: /
  controller: App\Controller\DefaultController::default

default_index:
  path: /index
  controller: App\Controller\DefaultController::index

app_info:
  path: /info
  controller: App\Controller\DefaultController::info

app_contact:
  path: /contact
  controller: App\Controller\DefaultController::contact

app_inbox:
  path: /inbox
  controller: App\Controller\InboxController::inbox

app_cart:
  path: /cart
  controller: App\Controller\CartController::cart
